### ISSUE TITLE
Feature: Blacklist

### ISSUE THREAD

**Issue by Tntdruid** [silviu20092/mod-improved-bank#3]
### Describe your feature request or suggestion in detail

Any plan too stop items like tools from going into bank?

**Comment by silviu20092** [comment]
Done in https://github.com/silviu20092/mod-improved-bank/commit/5bc00db75adff8b1df13ebeafe9b1be09ced6f7d

**Comment by Tntdruid** [comment]
Very nice. Thanks so much!
