### ISSUE TITLE
Bug: db migration failed

### ISSUE THREAD

**Issue by freekode** [silviu20092/mod-improved-bank#4]
### Current Behaviour

I cloned the module (didn't use it before), complied server and db migration fails with the log:
```
MySQL client library: 8.0.39
MySQL server ver: 8.3.0
Connected to MySQL database at ac-database
DatabasePool 'acore_world' opened successfully. 2 total connections running.

Updating Auth database...
>> Auth database is up-to-date! Containing 2 new and 0 archived updates.

ERROR 1146 (42S02) at line 1 in file: '/azerothcore/modules/mod-improved-bank/data/sql/db-characters/updates/MIB_2024_04_18_00.sql': Table 'acore_characters.mod_improved_bank' doesn't exist

Applying of file '/azerothcore/modules/mod-improved-bank/data/sql/db-characters/updates/MIB_2024_04_18_00.sql' to database 'acore_characters' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from AzerothCore repository with your sql client. If you are a developer, please fix your sql query.
Could not update the Character database, see log for details.
Updating Character database...
>> Applying update "MIB_2024_04_18_00.sql" '8F43F62'...
Closing down DatabasePool 'acore_world'.
Asynchronous connections on DatabasePool 'acore_world' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'acore_world' closed.
Closing down DatabasePool 'acore_characters'.
```

What I'm doing wrong? I understand that I can run sql with db creation manually, but why it won't execute automatically as it should be?

### Expected Behaviour

db migration should pass

### Steps to reproduce the problem

1. clone the repo to modules/mod-improved-bank
2. build images `docker compose build`
3. start containers `docker compose up -d`
4.  `✘ Container ac-db-import         service "ac-db-import" didn't complete successfully: exit 1`

### AC rev. hash/commit

-

### Operating system

docker, ubuntu 24.10

**Comment by silviu20092** [comment]
I remember an issue with docker not being able to import modules's sql files: https://github.com/azerothcore/azerothcore-wotlk/pull/19870
But this seems to be fixed. For some reason the base sql is not automatically imported, and you need to somehow manually import this file:
https://github.com/silviu20092/mod-improved-bank/tree/master/data/sql/db-characters/base

**Comment by freekode** [comment]
Thanks for the quick response. It seems I've found a problem.
SQL migrations sorted in wrong way
1. MIB_2024_04_18_00.sql
2. mod_improved_bank.sql

I renamed `MIB_2024_04_18_00.sql` to `xMIB_2024_04_18_00.sql` and everything migrated successfully

```

Updating Auth database...
>> Auth database is up-to-date! Containing 2 new and 0 archived updates.

Updating Character database...
>> Applying update "mod_improved_bank.sql" '724582D'...
>> Applying update "xMIB_2024_04_18_00.sql" '8F43F62'...
>> Applied 2 queries. Containing 7 new and 3 archived updates.

Updating World database...
>> Applying update "2024_11_07_05.sql" 'FF0C883'...
>> Applying update "2024_11_07_06.sql" '55B37DB'...
>> Applying update "MIB_2024_03_22_00.sql" '6B62F99'...
>> Applied 3 queries. Containing 1215 new and 3 archived updates.

Started database connection pool.
Halting process...
Closing down DatabasePool 'acore_characters'.
Asynchronous connections on DatabasePool 'acore_characters' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'acore_characters' closed.
```

I don't think base migrations should be sorted against updates

**Comment by silviu20092** [comment]
That is weird indeed, it seems that all updates were processed from the same folder. Maybe they were copied to /custom before, but definitely base folder should be processed first & separately from updates folder.
